package jframeproyecto;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin-Martinez
 */
public class adminFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminFrame
     */
    public adminFrame() {
        initComponents();
        setLocationRelativeTo(null);
        transparencia();
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_registrarDocente = new javax.swing.JButton();
        bt_modifyDocente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bt_deleteDocente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_mostrarAsistencias = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bt_mostrarDocentes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bt_cerrarCesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 183, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre.setText("ADMIN");
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 400, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTRAR DOCENTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 30));

        bt_registrarDocente.setBackground(new java.awt.Color(102, 183, 179));
        bt_registrarDocente.setForeground(new java.awt.Color(102, 183, 179));
        bt_registrarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile-fill (1).png"))); // NOI18N
        bt_registrarDocente.setBorderPainted(false);
        bt_registrarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarDocenteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_registrarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 113, -1));

        bt_modifyDocente.setBackground(new java.awt.Color(102, 183, 179));
        bt_modifyDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-fill.png"))); // NOI18N
        bt_modifyDocente.setBorderPainted(false);
        bt_modifyDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifyDocenteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_modifyDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 70, 70));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("MODIFICAR DOCENTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, 30));

        bt_deleteDocente.setBackground(new java.awt.Color(102, 183, 179));
        bt_deleteDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-bin-6-fill.png"))); // NOI18N
        bt_deleteDocente.setBorderPainted(false);
        bt_deleteDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteDocenteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_deleteDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ELIMINAR DOCENTE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, 60));

        bt_mostrarAsistencias.setBackground(new java.awt.Color(102, 183, 179));
        bt_mostrarAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/slideshow-fill.png"))); // NOI18N
        bt_mostrarAsistencias.setBorderPainted(false);
        bt_mostrarAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mostrarAsistenciasActionPerformed(evt);
            }
        });
        jPanel1.add(bt_mostrarAsistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("MOSTRAR ASISTENCIAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 277, 170, 30));

        bt_mostrarDocentes.setBackground(new java.awt.Color(102, 183, 179));
        bt_mostrarDocentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list-check-2.png"))); // NOI18N
        bt_mostrarDocentes.setBorderPainted(false);
        bt_mostrarDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mostrarDocentesActionPerformed(evt);
            }
        });
        jPanel1.add(bt_mostrarDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MOSTRAR DOCENTES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 130, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CERRAR SESION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 120, -1));

        bt_cerrarCesion.setBackground(new java.awt.Color(102, 183, 179));
        bt_cerrarCesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-2-fill.png"))); // NOI18N
        bt_cerrarCesion.setBorderPainted(false);
        bt_cerrarCesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_cerrarCesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarCesionActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cerrarCesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 328, 100, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarDocenteActionPerformed
        registroDocenteFrame VregistroDocente = new registroDocenteFrame();
        VregistroDocente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_registrarDocenteActionPerformed

    private void bt_modifyDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifyDocenteActionPerformed
        modificarDocenteFrame VModify = new modificarDocenteFrame();
        VModify.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_modifyDocenteActionPerformed

    private void bt_mostrarAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mostrarAsistenciasActionPerformed
        mostrarAsistenciasFrame VMostrar = new mostrarAsistenciasFrame();
        VMostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_mostrarAsistenciasActionPerformed

    private void bt_cerrarCesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarCesionActionPerformed
        iniciarSesionFrame VMain = new iniciarSesionFrame();
        VMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_cerrarCesionActionPerformed

    private void bt_deleteDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteDocenteActionPerformed
        eliminarDocenteFrame VDelete = new eliminarDocenteFrame();
        VDelete.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_deleteDocenteActionPerformed

    private void bt_mostrarDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mostrarDocentesActionPerformed
        mostrarDocentesFrame VMostrar = new mostrarDocentesFrame();
        VMostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_mostrarDocentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public void transparencia() {
        //--------REGISTRAR DOCENTE----
        bt_registrarDocente.setOpaque(false);
        bt_registrarDocente.setContentAreaFilled(false);
        bt_registrarDocente.setBorderPainted(false);
        // --------------MODIFICAR DOCENTE-----------
        bt_modifyDocente.setOpaque(false);
        bt_modifyDocente.setContentAreaFilled(false);
        bt_modifyDocente.setBorderPainted(false);
        // ------DELETE DOCENTE---------------
        bt_deleteDocente.setOpaque(false);
        bt_deleteDocente.setContentAreaFilled(false);
        bt_deleteDocente.setBorderPainted(false);
        //------MOSTRAR ASISTENCIA ---------------
        bt_mostrarAsistencias.setOpaque(false);
        bt_mostrarAsistencias.setContentAreaFilled(false);
        bt_mostrarAsistencias.setBorderPainted(false);
        //-----MOSTRAR DOCENTES------------
        bt_mostrarDocentes.setOpaque(false);
        bt_mostrarDocentes.setContentAreaFilled(false);
        bt_mostrarDocentes.setBorderPainted(false);
        //--------SALIR-------------
        bt_cerrarCesion.setOpaque(false);
        bt_cerrarCesion.setContentAreaFilled(false);
        bt_cerrarCesion.setBorderPainted(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cerrarCesion;
    private javax.swing.JButton bt_deleteDocente;
    private javax.swing.JButton bt_modifyDocente;
    private javax.swing.JButton bt_mostrarAsistencias;
    private javax.swing.JButton bt_mostrarDocentes;
    private javax.swing.JButton bt_registrarDocente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_nombre;
    // End of variables declaration//GEN-END:variables
}
