/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframeproyecto;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin-Martinez
 *
 */
public class docenteFrame extends javax.swing.JFrame {

    /**
     * Creates new form docenteFrame
     */
    public docenteFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        name();
        transparencia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BB_Interactiva = new javax.swing.JLabel();
        bt_registrarEntrada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bt_registrarSalida = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        salirDocente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        rSLabelHora1 = new rojeru_san.RSLabelHora();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 183, 179));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 368));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BB_Interactiva.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        BB_Interactiva.setForeground(new java.awt.Color(0, 0, 0));
        BB_Interactiva.setText("DOCENTE,");
        jPanel1.add(BB_Interactiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, 62));

        bt_registrarEntrada.setBackground(new java.awt.Color(102, 183, 179));
        bt_registrarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-check-fill.png"))); // NOI18N
        bt_registrarEntrada.setBorderPainted(false);
        bt_registrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(bt_registrarEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTRAR ENTRADA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        bt_registrarSalida.setBackground(new java.awt.Color(102, 183, 179));
        bt_registrarSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-box-r-line.png"))); // NOI18N
        bt_registrarSalida.setBorderPainted(false);
        bt_registrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(bt_registrarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("REGISTRAR SALIDA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        salirDocente.setBackground(new java.awt.Color(102, 183, 179));
        salirDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-2-fill.png"))); // NOI18N
        salirDocente.setBorderPainted(false);
        salirDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirDocenteActionPerformed(evt);
            }
        });
        jPanel1.add(salirDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CERRAR SESIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 120, -1));

        rSLabelFecha1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelFecha1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jPanel1.add(rSLabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 110, 40));

        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelHora1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jPanel1.add(rSLabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirDocenteActionPerformed
        iniciarSesionFrame VMain = new iniciarSesionFrame();
        VMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirDocenteActionPerformed

    private void bt_registrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarEntradaActionPerformed

        int pos = listaDocentes.BuscarXDni(iniciarSesionFrame.DniUs);

        String sHoraI = "7:30", sHoraF = "13:00";
        String sHoraE, sFechaE;

        if (listaDocentes.arrListDocente.get(pos).getHoraEntrada().length() == 0) {
            int rpta;

            //<------------VALIDAR REGISTRO--------------------------------->
            rpta = JOptionPane.showOptionDialog(null, "Desea registrar entrada? ", //contenido de la ventana
                    "Entrada", //titulo de la ventana
                    JOptionPane.YES_NO_OPTION, //para 2 botones si/no
                    JOptionPane.QUESTION_MESSAGE, //tipo de ícono
                    null, // null para icono por defecto.
                    new Object[]{"SÍ", "NO"},//objeto para las opciones
                    "SÍ"); //selección predeterminada
            //-----------------------------------------------------------

            if (rpta == 0) {
                DateFormat dateH = new SimpleDateFormat("HH:mm");
                sHoraE = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));
                sFechaE = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                try {
                    Date horaI;
                    horaI = dateH.parse(sHoraI);
                    Date horaF;
                    horaF = dateH.parse(sHoraF);
                    Date horaE = dateH.parse(sHoraE);

                    String datos = "ENTRADA" + " Hora: " + sHoraE + " Fecha: " + sFechaE;
                    listaDocentes.arrListDocente.get(pos).setHoraEntrada(datos);

                    if (horaE.before(horaI)) {
                        listaDocentes.arrListDocente.get(pos).setEstadoEntrada("PUNTUAL");
                        JOptionPane.showMessageDialog(null, "Entrada registrada exitosamente" + "\n Hora: " + sHoraE + "\n Fecha: " + sFechaE + "\n" + "\n" + "PUNTUAL");
                    } else {
                        listaDocentes.arrListDocente.get(pos).setEstadoEntrada("TARDANZA");
                        JOptionPane.showMessageDialog(null, "Entrada registrada exitosamente" + "\n Hora: " + sHoraE + "\n Fecha: " + sFechaE + "\n" + "\n" + "TARDANZA");

                    }

                } catch (ParseException ex) {
                    Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Usted ya tiene registrada una hora de ingreso en el dia ");
        }
    }//GEN-LAST:event_bt_registrarEntradaActionPerformed

    private void bt_registrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarSalidaActionPerformed

        int pos = listaDocentes.BuscarXDni(iniciarSesionFrame.DniUs);

        String sHoraI = "7:30", sHoraF = "13:00";
        String sHoraS, sFechaS;

        if (listaDocentes.arrListDocente.get(pos).getHoraSalida().length() == 0) {
            if (listaDocentes.arrListDocente.get(pos).getHoraEntrada().length() > 0) {
                int rpta;

                //<------------VALIDAR REGISTRO--------------------------------->
                rpta = JOptionPane.showOptionDialog(null, "¿Desea registrar salida? ", //contenido de la ventana
                        "Salida", //titulo de la ventana
                        JOptionPane.YES_NO_OPTION, //para 2 botones si/no
                        JOptionPane.QUESTION_MESSAGE, //tipo de ícono
                        null, // null para icono por defecto.
                        new Object[]{"SÍ", "NO"},//objeto para las opciones
                        "SÍ"); //selección predeterminada
                //-----------------------------------------------------------

                if (rpta == 0) {
                    DateFormat dateH = new SimpleDateFormat("HH:mm");
                    sHoraS = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));
                    sFechaS = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                    try {
                        Date horaI;
                        horaI = dateH.parse(sHoraI);
                        Date horaF;
                        horaF = dateH.parse(sHoraF);
                        Date horaS = dateH.parse(sHoraS);

                        String datos = "SALIDA" + " Hora: " + sHoraS + " Fecha: " + sFechaS;

                        listaDocentes.arrListDocente.get(pos).setHoraSalida(datos);

                        if (horaS.before(horaF)) {
                            listaDocentes.arrListDocente.get(pos).setEstadoSalida("PREMATURA");
                            JOptionPane.showMessageDialog(null, "Salida prematura registrada exitosamente" + "\n Hora: " + sHoraS + "\n Fecha: " + sFechaS + "\n" + "\n" + "PREMATURA");
                        } else {
                            listaDocentes.arrListDocente.get(pos).setEstadoSalida("REGISTRADA");
                            JOptionPane.showMessageDialog(null, "Salida registrada existosamente" + "\n Hora: " + sHoraS + "\n Fecha: " + sFechaS + "\n" + "\n" + "REGISTRADA");
                        }

                    } catch (ParseException ex) {
                        Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Tiene que registrar primero su hora de entrada");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usted ya tiene registrada una hora de salida en el día ");
        }

    }//GEN-LAST:event_bt_registrarSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void name() {

        listaDocentes obj = new listaDocentes();
        BB_Interactiva.setText("Hola, " + listaDocentes.arrListDocente.get(obj.BuscarXDni(iniciarSesionFrame.DniUs)).getNombre());
        BB_Interactiva.setHorizontalAlignment(0);

    }

    public void transparencia() {
        //--------REGISTRAR ENTRADA-----------
        bt_registrarEntrada.setOpaque(false);
        bt_registrarEntrada.setContentAreaFilled(false);
        bt_registrarEntrada.setBorderPainted(false);
        //-----------REGISTRAR SALIDA-------
        bt_registrarSalida.setOpaque(false);
        bt_registrarSalida.setContentAreaFilled(false);
        bt_registrarSalida.setBorderPainted(false);
        //--------SALIR--------------------
        salirDocente.setOpaque(false);
        salirDocente.setContentAreaFilled(false);
        salirDocente.setBorderPainted(false);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(docenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(docenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(docenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(docenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new docenteFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BB_Interactiva;
    private javax.swing.JButton bt_registrarEntrada;
    private javax.swing.JButton bt_registrarSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    private javax.swing.JButton salirDocente;
    // End of variables declaration//GEN-END:variables
}
