/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframeproyecto;

import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author Kevin-Martinez
 */
public class eliminarDocenteFrame extends javax.swing.JFrame {

    /**
     * Creates new form registroDocente
     */
    public eliminarDocenteFrame() {
        initComponents();
        setLocationRelativeTo(null);
        grupo_Sexo.add(bt_masculino);
        grupo_Sexo.add(bt_femenino);
        this.setResizable(false);
    }
    public int pos;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Sexo = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dniDocente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        claveDocente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreDocente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bt_eliminar = new javax.swing.JButton();
        apellidosDocente = new javax.swing.JTextField();
        aulaDocente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bt_volver = new javax.swing.JButton();
        bt_masculino = new javax.swing.JRadioButton();
        bt_femenino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        dniDelete = new javax.swing.JTextField();
        bt_buscar = new javax.swing.JButton();
        bt_volver1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 183, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ELIMINAR DOCENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 390, 80));

        dniDocente.setEditable(false);
        dniDocente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(dniDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("AULA: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("SEXO (F/M):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CLAVE: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        claveDocente.setEditable(false);
        claveDocente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(claveDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOMBRE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 20));

        nombreDocente.setEditable(false);
        nombreDocente.setBackground(new java.awt.Color(204, 204, 204));
        nombreDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDocenteActionPerformed(evt);
            }
        });
        jPanel1.add(nombreDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("APELLIDOS: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        bt_eliminar.setBackground(new java.awt.Color(255, 102, 102));
        bt_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        bt_eliminar.setText("ELIMINAR");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 100, 40));

        apellidosDocente.setEditable(false);
        apellidosDocente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(apellidosDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 150, -1));

        aulaDocente.setEditable(false);
        aulaDocente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(aulaDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 150, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DNI: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        bt_volver.setBackground(new java.awt.Color(255, 102, 102));
        bt_volver.setForeground(new java.awt.Color(0, 0, 0));
        bt_volver.setText("VOLVER");
        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        jPanel1.add(bt_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 100, 40));

        bt_masculino.setBackground(new java.awt.Color(102, 183, 179));
        bt_masculino.setForeground(new java.awt.Color(0, 0, 0));
        bt_masculino.setText("Masculino");
        bt_masculino.setEnabled(false);
        jPanel1.add(bt_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 30));

        bt_femenino.setBackground(new java.awt.Color(102, 183, 179));
        bt_femenino.setForeground(new java.awt.Color(0, 0, 0));
        bt_femenino.setText("Femenino");
        bt_femenino.setEnabled(false);
        jPanel1.add(bt_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ingrese DNI a eliminar: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        dniDelete.setBackground(new java.awt.Color(204, 204, 204));
        dniDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(dniDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 140, 30));

        bt_buscar.setBackground(new java.awt.Color(255, 102, 102));
        bt_buscar.setForeground(new java.awt.Color(0, 0, 0));
        bt_buscar.setText("BUSCAR");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 90, 30));

        bt_volver1.setBackground(new java.awt.Color(255, 102, 102));
        bt_volver1.setForeground(new java.awt.Color(0, 0, 0));
        bt_volver1.setText("VOLVER");
        bt_volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volver1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDocenteActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed

        boolean okey = validarCampos(dniDocente.getText(), nombreDocente.getText(), apellidosDocente.getText(), claveDocente.getText(), aulaDocente.getText());

        if (okey) {

            String dni = dniDocente.getText();
            String nombre = nombreDocente.getText();
            String apellidos = apellidosDocente.getText();
            String sexo = "";
            if (bt_femenino.isSelected()) {
                sexo = "Femenino";
            } else if (bt_masculino.isSelected()) {
                sexo = "Masculino";
            } else {
                sexo = "No se seleciono";
            }

            String aula = aulaDocente.getText();
            String clave = claveDocente.getText();

            listaDocentes.arrListDocente.remove(pos);
            JOptionPane.showMessageDialog(null, "Eliminación Exitosa");
            grupo_Sexo.clearSelection();
            dniDocente.setText("");
            nombreDocente.setText("");
            apellidosDocente.setText("");
            aulaDocente.setText("");
            claveDocente.setText("");
            dniDelete.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed

    public static boolean validarCampos(String nombre, String apellido, String dni, String clave, String aula) {
        boolean okey = false;

        if (nombre.length() > 0 && apellido.length() > 0 && dni.length() > 0 && clave.length() > 0 && aula.length() > 0) {
            okey = true;
        }
        return okey;
    }

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        adminFrame VadminFrame = new adminFrame();
        VadminFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_volverActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed

        String dniM = dniDelete.getText();

        listaDocentes obj = new listaDocentes();
        pos = obj.BuscarXDni(dniM);
        if (pos != -1) {
            nombreDocente.setText(listaDocentes.arrListDocente.get(pos).getNombre());
            apellidosDocente.setText(listaDocentes.arrListDocente.get(pos).getApellidos());
            dniDocente.setText(listaDocentes.arrListDocente.get(pos).getDNI());
            aulaDocente.setText(listaDocentes.arrListDocente.get(pos).getAula());
            claveDocente.setText(listaDocentes.arrListDocente.get(pos).getClave());

            if ("Femenino".equals(listaDocentes.arrListDocente.get(pos).getSexo())) {
                bt_femenino.setSelected(true);
            } else if ("Masculino".equals(listaDocentes.arrListDocente.get(pos).getSexo())) {
                bt_masculino.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "DNI no encontrado");
            grupo_Sexo.clearSelection();
            dniDocente.setText("");
            nombreDocente.setText("");
            apellidosDocente.setText("");
            aulaDocente.setText("");
            claveDocente.setText("");
        }
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void dniDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniDeleteActionPerformed

    private void bt_volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_volver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminarDocenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminarDocenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminarDocenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminarDocenteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new eliminarDocenteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosDocente;
    private javax.swing.JTextField aulaDocente;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JRadioButton bt_femenino;
    private javax.swing.JRadioButton bt_masculino;
    private javax.swing.JButton bt_volver;
    private javax.swing.JButton bt_volver1;
    private javax.swing.JTextField claveDocente;
    private javax.swing.JTextField dniDelete;
    private javax.swing.JTextField dniDocente;
    private javax.swing.ButtonGroup grupo_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreDocente;
    // End of variables declaration//GEN-END:variables
}
