/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframeproyecto;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin-Martinez
 */
public class iniciarSesionFrame extends javax.swing.JFrame {

    public static String fechaHoy;
    public static String fechaHoytxt;
    public static String DniUs;

    /**
     * Creates new form Proyecto
     */
    public iniciarSesionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        SimpleDateFormat dtf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar calendar = Calendar.getInstance();
        Date dateObj = calendar.getTime();
        fechaHoy = dtf.format(dateObj);

        SimpleDateFormat dtf2 = new SimpleDateFormat("dd-MM-yyyy");
        fechaHoytxt = dtf2.format(dateObj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JPanel();
        dni = new javax.swing.JLabel();
        clave = new javax.swing.JLabel();
        dniInp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enviarBt = new javax.swing.JButton();
        claveInp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID.setBackground(new java.awt.Color(102, 183, 179));

        dni.setBackground(new java.awt.Color(0, 0, 0));
        dni.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        dni.setForeground(new java.awt.Color(0, 0, 0));
        dni.setText("Ingrese DNI:");

        clave.setBackground(new java.awt.Color(0, 0, 0));
        clave.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        clave.setForeground(new java.awt.Color(0, 0, 0));
        clave.setText("Ingrese clave: ");

        dniInp.setBackground(new java.awt.Color(255, 255, 255));
        dniInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniInpActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INICIAR SESIÓN");

        enviarBt.setBackground(new java.awt.Color(51, 51, 51));
        enviarBt.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        enviarBt.setForeground(new java.awt.Color(255, 255, 255));
        enviarBt.setText("INGRESAR");
        enviarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBtActionPerformed(evt);
            }
        });

        claveInp.setBackground(new java.awt.Color(255, 255, 255));
        claveInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveInpActionPerformed(evt);
            }
        });
        claveInp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                claveInpKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout IDLayout = new javax.swing.GroupLayout(ID);
        ID.setLayout(IDLayout);
        IDLayout.setHorizontalGroup(
            IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDLayout.createSequentialGroup()
                .addGroup(IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IDLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IDLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IDLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(enviarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(IDLayout.createSequentialGroup()
                                .addGroup(IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clave))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dniInp)
                                    .addComponent(claveInp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        IDLayout.setVerticalGroup(
            IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni)
                    .addComponent(dniInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clave)
                    .addComponent(claveInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(enviarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        clave.getAccessibleContext().setAccessibleParent(clave);
        dniInp.getAccessibleContext().setAccessibleName("IDInt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String idAdmin = "000";
    String claveAdmin = "1234";
    private void dniInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniInpActionPerformed


    }//GEN-LAST:event_dniInpActionPerformed

    private void iniciarSesion() {
        DniUs = dniInp.getText();
        String numClave = claveInp.getText();

        listaDocentes obj = new listaDocentes();

        if (DniUs.equals(idAdmin) && numClave.equals(claveAdmin)) {
            adminFrame VAdmin = new adminFrame();
            VAdmin.setVisible(true);
            this.setVisible(false);
            
        } else if ((obj.BuscarXDni(DniUs) == obj.BuscarXClave(numClave)) && obj.BuscarXDni(DniUs) != -1) {
            docenteFrame VDocente = new docenteFrame();
            VDocente.setVisible(true);
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "DNI o clave incorrecta");
            claveInp.setText("");
        }
    }

    private void enviarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBtActionPerformed

        iniciarSesion();

    }//GEN-LAST:event_enviarBtActionPerformed

    private void claveInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveInpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveInpActionPerformed

    private void claveInpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveInpKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            iniciarSesion();
        }
    }//GEN-LAST:event_claveInpKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciarSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciarSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciarSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciarSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciarSesionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ID;
    private javax.swing.JLabel clave;
    private javax.swing.JPasswordField claveInp;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField dniInp;
    private javax.swing.JButton enviarBt;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
