/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframeproyecto;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin-Martinez
 */
public class mostrarDocentesFrame extends javax.swing.JFrame {

    public static DefaultTableModel modelo;
    private static String[] info;

    /**
     * Creates new form mostrarAsistenciasFrame
     */
    public mostrarDocentesFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("SEXO");
        modelo.addColumn("AULA");

        this.tabla.setModel(modelo);
        listaDocentes obj = new listaDocentes();
        for (int i = 0; i < listaDocentes.arrListDocente.size(); i++) {

            info = new String[5];

            info[0] = listaDocentes.arrListDocente.get(i).getDNI();
            info[1] = listaDocentes.arrListDocente.get(i).getNombre();
            info[2] = listaDocentes.arrListDocente.get(i).getApellidos();
            info[3] = listaDocentes.arrListDocente.get(i).getSexo();
            info[4] = listaDocentes.arrListDocente.get(i).getAula();
            
            modelo.addRow(info);
        }

    }

    private void actualizarTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("SEXO");
        modelo.addColumn("AULA");

        this.tabla.setModel(modelo);
        listaDocentes obj = new listaDocentes();
        for (int i = 0; i < listaDocentes.arrListDocente.size(); i++) {

            info = new String[5];

            info[0] = listaDocentes.arrListDocente.get(i).getDNI();
            info[1] = listaDocentes.arrListDocente.get(i).getNombre();
            info[2] = listaDocentes.arrListDocente.get(i).getApellidos();
            info[3] = listaDocentes.arrListDocente.get(i).getSexo();
            info[4] = listaDocentes.arrListDocente.get(i).getAula();
            modelo.addRow(info);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        bt_volver = new javax.swing.JButton();
        bt_cargar = new javax.swing.JButton();
        bt_g_doc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 183, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DOCENTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        rSLabelFecha1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(rSLabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 50));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1050, 480));

        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(rSLabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 50));

        bt_volver.setBackground(new java.awt.Color(255, 102, 102));
        bt_volver.setForeground(new java.awt.Color(0, 0, 0));
        bt_volver.setText("VOLVER");
        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        jPanel1.add(bt_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 100, 40));

        bt_cargar.setBackground(new java.awt.Color(255, 102, 102));
        bt_cargar.setForeground(new java.awt.Color(0, 0, 0));
        bt_cargar.setText("CARGAR DOCENTES");
        bt_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cargarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, 40));

        bt_g_doc.setBackground(new java.awt.Color(255, 102, 102));
        bt_g_doc.setForeground(new java.awt.Color(0, 0, 0));
        bt_g_doc.setText("GUARDAR DOCENTES");
        bt_g_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_g_docActionPerformed(evt);
            }
        });
        jPanel1.add(bt_g_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        adminFrame VadminFrame = new adminFrame();
        VadminFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_volverActionPerformed

    private void bt_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cargarActionPerformed
        try {
            Datos.cargarDocentes();
        } catch (IOException ex) {
            Logger.getLogger(mostrarDocentesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Docentes cargados exitosamente: " + iniciarSesionFrame.fechaHoy);

        actualizarTabla();
    }//GEN-LAST:event_bt_cargarActionPerformed

    private void bt_g_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_g_docActionPerformed
        try {
            Datos.guardarDocentes();
        } catch (IOException ex) {
            Logger.getLogger(mostrarDocentesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Docentes guardados exitosamente: " + iniciarSesionFrame.fechaHoy);
    }//GEN-LAST:event_bt_g_docActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mostrarDocentesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mostrarDocentesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mostrarDocentesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mostrarDocentesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mostrarDocentesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cargar;
    private javax.swing.JButton bt_g_doc;
    private javax.swing.JButton bt_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
